rails_tutorial:
  home: "https://www.railstutorial.org/"
  help: "https://www.railstutorial.org/help"
  book: "https://www.railstutorial.org/book"
  contact: "https://www.railstutorial.org/contact"
  new: "http://news.railstutorial.org/"
  screencasts: "https://screencasts.railstutorial.org/"
  michael_hartl: "http://www.michaelhartl.com/"
learn_enough: "https://www.learnenough.com/"
image:
  rails: rails.png
user:
  names:
    max_length: 50
  email:
    max_length: 250
    regex_valid: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  password:
    min_length: 6
  gravatar:
    size: 80
    url: "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    edit: "http://gravatar.com/emails"
  password_reset:
    expired: 2
paginate:
  record_per_page: 5
  theme: "twitter-bootstrap-3"
session:
  check_box: "1"
mailer:
  host: "localhost:3000"
  protocol: "http"
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  user_name: "phu.dv1998@gmail.com"
  password: "mwvxitiyuxrhmibo"
  authentication: "plain"
micropost:
  content:
    max_length: 140
  show:
    feed_items: 5
  gravatar:
    size: 50
  picture:
    resize_limit: [200, 200]
    accept: "image/jpeg,image/gif,image/png"
